### ISSUE TITLE
Damage Telemetry Data Possible?

### ISSUE THREAD

**Issue by thumpnail** [richstokes/Forza-data-tools#2]
i am wondering if the telemetry data is outputting som Damage data and if it could make it in the tool?

**Comment by j-toscani** [comment]
Hi @thumpnail,

if you are asking for FM7-Data than you are out of luck. They do not provide it. 

In this Post from TURN10 in the official Forums, you can see what Data is available: https://forums.forzamotorsport.net/turn10_postst128499_Forza-Motorsport-7--Data-Out--feature-details.aspx. 

Cheers!
