### ISSUE TITLE
undefined serveJSON

### ISSUE THREAD

**Issue by markusjdev** [richstokes/Forza-data-tools#3]
I can't get the JSON-Server running.

cmd:
```

C:\Users\User1\Downloads\Forza-data-tools-master\Forza-data-tools-master>go run main.go -z
# command-line-arguments
.\main.go:328:6: undefined: serveJSON

```

Why it's undefined? It's defined in the other files.

Thank you in advance.

**Comment by vinjn** [comment]
This command might help
> go env -w GO111MODULE=auto

**Comment by richstokes** [comment]
If anyone would like to PR any changes to the readme with better instructions for getting started, feel free! I'm not an expert with go modules / environment setup :-)
